version: '3.9'

services:
    mariadb:
        image: mariadb:image
        build:
          context: ./requirements/mariadb
        container_name: mariadb
        volumes:
            - database:/var/lib/mysql
        expose:
            - "3306"
        networks:
            - app-network
        env_file:
            - .env
        restart: always

    wordpress:
        image: wordpress:image
        build:
            context: ./requirements/wordpress
        container_name: wordpress
        volumes:
            - wordpress:/var/www/wordpress
        depends_on:
            - mariadb
        expose:
            - "9000"
        networks:
            - app-network
        env_file:
            - .env
        restart: always

    nginx:
        image: nginx:image
        build:
          context: ./requirements/nginx
        container_name: nginx
        volumes:
            - wordpress:/var/www/wordpress
        depends_on:
            - wordpress
        ports:
            - "443:443"
        networks:
            - app-network
        restart: always

volumes:
    database:
        name: database
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/${USER}/data/database
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/${USER}/data/wordpress

networks:
    app-network:
        name: app-network
        driver: bridge