version '3.8'

services:
    mariadb:
        env_file:
            - .env

    wordpress:
        env_file:
            - .env

    nginx:
        ports:
            - "443:443"
        networks:
            - app-network

volumes:
    dbdata:

    wordpress:

networks:
    app-newtork: