version: '3.9'

services:
    mariadb:
        image: mariadb:image
        build:
          context: ./requirements/mariadb
        container_name: mariadb
        volumes:
            - database:/var/lib/mysql
        expose:
            - "3306"
        networks:
            - docker-network
        env_file:
            - .env
        restart: always

    wordpress:
        image: wordpress:image
        build:
            context: ./requirements/wordpress
        container_name: wordpress
        volumes:
            - wordpress:/var/www/wordpress
        depends_on:
            - mariadb
        expose:
            - "9000"
        networks:
            - docker-network
        env_file:
            - .env
        restart: always

    nginx:
        image: nginx:image
        build:
          context: ./requirements/nginx
        container_name: nginx
        volumes:
            - wordpress:/var/www/wordpress
        depends_on:
            - wordpress
        ports:
            - "443:443"
        networks:
            - docker-network
        restart: always

    cv:
        image: cv:image
        build:
            context: ./requirements/bonus/cv
        container_name: cv
        ports:
            - "8081:8081"
        networks:
            - docker-network
        restart: always

    redis:
        image: redis:image
        build:
            context: ./requirements/bonus/redis
        container_name: redis
        volumes:
            - wordpress:/var/www/wordpress
        depends_on:
            - wordpress
        expose:
            - "6379"
        networks:
            - docker-network
        restart: always
    
    ftp:
        image: ftp:image
        build:
            context: ./requirements/bonus/ftp
        container_name: ftp
        volumes:
            - wordpress:/var/www/wordpress
        depends_on:
            - wordpress
        ports:
            - "21:21"
        networks:
            - docker-network
        env_file:
            - .env
        restart: always

    adminer:
        image: adminer:image
        build:
            context: ./requirements/bonus/adminer
        container_name: adminer
        depends_on:
            - wordpress
            - mariadb
        ports:
            - "8082:8082"
        networks:
            - docker-network
        restart: always

    nodejs:
        image: nodejs:image
        build:
            context: ./requirements/bonus/nodejs
        container_name: nodejs
        networks:
        - inception
        env_file:
        - .env
        restart: always

    minecraft:
        image: minecraft:image
        build:
            context: ./requirements/bonus/minecraft
        container_name: minecraft
        volumes:
            - minecraft:/var/www/minecraft
        ports:
            - "25565:25565"
        networks:
            - docker-network
        restart: always


volumes:
    database:
        name: database
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/${USER}/data/database
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/${USER}/data/wordpress
    minecraft:
        name: minecraft
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/${USER}/data/minecraft

networks:
    docker-network:
        name: docker-network
        driver: bridge